### ISSUE TITLE
MVP ToDo (For presentation)

### ISSUE THREAD

**Issue by c-phillips7** [mkohn4/keep#12]
- [x] Set up done to update db
- [x]  map (filter) based on if done:true
- [x] Fix readme
- [ ] Presentation with user story
- [ ] add an about page
